# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjFqDekoG94TQinnaZ4KTw8dRbM9RNiD
"""

print("1.When did India got independence? ")
print("a. 1947 b. 1902 c. 1958 d. 1999")
answer=input("Enter your option: ")
if answer == "a":
  print("Well Done! That's a correct answer!")
else:
  print("The correct answer is option a. '1947'")